from pathlib import Path
from itertools import combinations
import sys
import zipfile
import time

import numpy as np
import pandas as pd
from scipy import stats

# ------------------------------------------------------------
# Local project paths
# ------------------------------------------------------------
# The original version of this script was executed in ChatGPT's sandbox,
# where /mnt/data exists.  On your Mac, use paths relative to the project
# instead.  This block also works if the script is placed either in the
# project root or in statistical_analysis_results/.

SCRIPT_DIR = Path(__file__).resolve().parent

ROOT = None
for candidate in (SCRIPT_DIR, SCRIPT_DIR.parent):
    if (candidate / 'rs_sensitivity_results').exists():
        ROOT = candidate
        break
    if (candidate / 'statistical_analysis.py').exists():
        ROOT = candidate
        break

if ROOT is None:
    ROOT = SCRIPT_DIR

# Master 1,500-row sensitivity file generated by
# run_rs_sensitivity_slow_fast_fixed.py.
master_candidates = [
    ROOT / 'rs_sensitivity_results' / 'rs_sensitivity_all_profiles.csv',
    ROOT / 'rs_sensitivity_all_profiles.csv',
    SCRIPT_DIR / 'rs_sensitivity_all_profiles.csv',
]

MASTER = next((p for p in master_candidates if p.exists()), None)
if MASTER is None:
    checked = '\n'.join(f'  - {p}' for p in master_candidates)
    raise FileNotFoundError(
        'Could not find rs_sensitivity_all_profiles.csv. Checked:\n' + checked
    )

# Put the outputs with the other statistical-analysis files.
ANALYSIS_ROOT = ROOT / 'statistical_analysis_results'
ANALYSIS_ROOT.mkdir(parents=True, exist_ok=True)
OUT = ANALYSIS_ROOT / 'sensitivity_all_profiles_analysis'
OUT.mkdir(parents=True, exist_ok=True)

# Import the exact helper functions from the prior analysis scripts.
# Search both the project root and statistical_analysis_results/.
for search_dir in (ROOT, ANALYSIS_ROOT, SCRIPT_DIR):
    search_str = str(search_dir)
    if search_str not in sys.path:
        sys.path.insert(0, search_str)

try:
    import statistical_analysis as prep
    import step5_confidence_intervals as step5
    import step6_normality_checks as step6
    import step7_outlier_analysis_fixed as step7
    import step9_significance_rs as step9
    import step10_timeout_censoring as step10
except ModuleNotFoundError as exc:
    raise ModuleNotFoundError(
        'A required helper script could not be imported. Expected these files '
        'in the project root or statistical_analysis_results/: '
        'statistical_analysis.py, step5_confidence_intervals.py, '
        'step6_normality_checks.py, step7_outlier_analysis_fixed.py, '
        'step9_significance_rs.py, and step10_timeout_censoring.py.'
    ) from exc

print(f'Project root: {ROOT}')
print(f'Input file:   {MASTER}')
print(f'Output dir:   {OUT}', flush=True)

T0 = time.perf_counter()
print('[1/8] Loading and validating the 1,500-row sensitivity dataset...', flush=True)

# -----------------------
# 1. Analysis-ready data
# -----------------------
prep.SENSITIVITY_RESULTS_CSV = MASTER
df = prep.load_sensitivity_results()

expected_profiles = {('Slow',0,43), ('Moderate',1,62), ('Fast',2,62)}
observed_profiles = set(map(tuple, df[['Profile','SMF','L']].drop_duplicates().itertuples(index=False, name=None)))
if observed_profiles != expected_profiles:
    raise ValueError(f'Unexpected profile/L coverage: {observed_profiles}')

expected_settings = {(1,3),(2,3),(3,3),(1,4),(1,5)}
for key, g in df.groupby(['Profile','SMF','L']):
    settings = set(map(tuple, g[['r','s']].drop_duplicates().astype(int).itertuples(index=False, name=None)))
    if settings != expected_settings:
        raise ValueError(f'{key}: settings mismatch {settings}')
    counts = g.groupby(['Run','Seed']).size()
    if not (counts == 5).all() or len(counts) != 100:
        raise ValueError(f'{key}: incomplete paired design')

if not (df['Status'] == 'OK').all():
    print('WARNING: non-OK rows present:', df['Status'].value_counts().to_dict())

analysis_ready = OUT / 'rs_sensitivity_analysis_ready_all_profiles.csv'
df.to_csv(analysis_ready, index=False)

print(f'[1/8] Done in {time.perf_counter()-T0:.2f} s. Rows={len(df)}', flush=True)
print('[2/8] Computing means, SEs, medians, and 10,000-resample bootstrap CIs...', flush=True)
T2=time.perf_counter()

# ----------------------------------------------
# 2. SE / percentile-bootstrap 95% CI / medians
# ----------------------------------------------
# Run each profile separately with the same bootstrap seed as the prior Moderate-only
# analysis. This preserves the already reported Moderate bootstrap results while applying
# exactly the same protocol independently to the new Slow and Fast profiles.
ci_parts = []
for key, g in df.groupby(['Profile','SMF','L'], sort=True):
    part = step5.summarize_dataset(
        g,
        group_columns=['Profile','SMF','L','r','s'],
        dataset_label=f'Sensitivity dataset {key}',
    )
    ci_parts.append(part)
ci_full = pd.concat(ci_parts, ignore_index=True).sort_values(['Profile','SMF','L','r','s']).reset_index(drop=True)
ci_paper = step5.make_paper_friendly_table(ci_full, ['Profile','SMF','L','r','s'])
ci_full.to_csv(OUT/'rs_sensitivity_se_ci_full_all_profiles.csv', index=False)
ci_paper.to_csv(OUT/'rs_sensitivity_se_ci_paper_all_profiles.csv', index=False)

print(f'[2/8] Done in {time.perf_counter()-T2:.2f} s.', flush=True)
print('[3/8] Running Shapiro-Wilk, skewness, and kurtosis diagnostics...', flush=True)
T3=time.perf_counter()

# -------------------
# 3. Normality checks
# -------------------
# No Q-Q plot generation here; statistics reproduce the prior Shapiro/skew/kurtosis protocol.
norm_rows=[]
for key, g in df.groupby(['Profile','SMF','L','r','s'], sort=True):
    info=dict(zip(['Profile','SMF','L','r','s'], key))
    for col, metric in step6.METRICS.items():
        row=info.copy(); row['Metric']=metric; row.update(step6.normality_statistics(g[col])); norm_rows.append(row)
normality = pd.DataFrame(norm_rows).sort_values(['Profile','SMF','L','r','s','Metric']).reset_index(drop=True)
normality.to_csv(OUT/'rs_sensitivity_normality_paper_all_profiles.csv', index=False)

print(f'[3/8] Done in {time.perf_counter()-T3:.2f} s.', flush=True)
print('[4/8] Computing Tukey 1.5 x IQR outlier diagnostics...', flush=True)
T4=time.perf_counter()

# -----------------
# 4. Tukey outliers
# -----------------
outlier_summary, outlier_obs = step7.analyze_dataset(
    df,
    group_columns=['Profile','SMF','L','r','s'],
    dataset_label='Sensitivity dataset all profiles',
)
outlier_paper = step7.make_compact_table(outlier_summary, ['Profile','SMF','L','r','s'])
outlier_summary.to_csv(OUT/'rs_sensitivity_outlier_summary_full_all_profiles.csv', index=False)
outlier_paper.to_csv(OUT/'rs_sensitivity_outlier_summary_paper_all_profiles.csv', index=False)
outlier_obs.to_csv(OUT/'rs_sensitivity_outlier_observations_all_profiles.csv', index=False)

print(f'[4/8] Done in {time.perf_counter()-T4:.2f} s.', flush=True)
print('[5/8] Running paired Friedman and Holm-adjusted Wilcoxon tests...', flush=True)
T5=time.perf_counter()

# ------------------------------------------------------
# 5. Profile-stratified paired Friedman/Wilcoxon analyses
# ------------------------------------------------------
all_desc=[]; all_omni=[]; all_pair=[]; all_complete=[]; all_status=[]
for (profile, smf, L), g in df.groupby(['Profile','SMF','L'], sort=True):
    for fam_name, settings in [('r sensitivity (s=3)', step9.R_SETTINGS), ('s sensitivity (r=1)', step9.S_SETTINGS)]:
        desc, omni, pair, complete = step9.analyze_family(g, fam_name, settings)
        for frame in (desc, omni, pair, complete):
            frame.insert(0,'L',int(L)); frame.insert(0,'SMF',int(smf)); frame.insert(0,'Profile',profile)
        all_desc.append(desc); all_omni.append(omni); all_pair.append(pair); all_complete.append(complete)
    status = step9.make_status_counts(g)
    status.insert(0,'L',int(L)); status.insert(0,'SMF',int(smf)); status.insert(0,'Profile',profile)
    all_status.append(status)

paired_desc=pd.concat(all_desc,ignore_index=True)
omnibus=pd.concat(all_omni,ignore_index=True)
pairwise=pd.concat(all_pair,ignore_index=True)
complete=pd.concat(all_complete,ignore_index=True)
status_counts=pd.concat(all_status,ignore_index=True)

paired_desc.to_csv(OUT/'rs_paired_descriptives_all_profiles.csv',index=False)
omnibus.to_csv(OUT/'rs_friedman_tests_all_profiles.csv',index=False)
pairwise.to_csv(OUT/'rs_pairwise_wilcoxon_all_profiles.csv',index=False)
complete.to_csv(OUT/'rs_complete_case_counts_all_profiles.csv',index=False)
status_counts.to_csv(OUT/'rs_status_counts_all_profiles.csv',index=False)

print(f'[5/8] Done in {time.perf_counter()-T5:.2f} s.', flush=True)
print('[6/8] Computing censoring-aware runtime summaries and paired sign tests...', flush=True)
T6=time.perf_counter()

# ----------------------------------------------
# 6. Profile-stratified censoring-aware summaries
# ----------------------------------------------
surv = step10.prepare_runtime_data(df, 'Sensitivity dataset all profiles')
surv_summary = step10.sensitivity_survival_summary(surv)
paired_censor=[]
for (profile, smf, L), g in surv.groupby(['Profile','SMF','L'], sort=True):
    for fam_name, settings in [('r sensitivity (s=3)', step10.R_SETTINGS), ('s sensitivity (r=1)', step10.S_SETTINGS)]:
        rows=step10.analyze_paired_censoring_family(g, fam_name, settings)
        for row in rows:
            row['Profile']=profile; row['SMF']=int(smf); row['L']=int(L)
            paired_censor.append(row)
paired_censor=pd.DataFrame(paired_censor)
if not paired_censor.empty:
    cols=['Profile','SMF','L']+[c for c in paired_censor.columns if c not in {'Profile','SMF','L'}]
    paired_censor=paired_censor[cols]
surv_summary.to_csv(OUT/'rs_survival_summary_all_profiles.csv',index=False)
paired_censor.to_csv(OUT/'rs_paired_censoring_sign_tests_all_profiles.csv',index=False)

print(f'[6/8] Done in {time.perf_counter()-T6:.2f} s.', flush=True)
print('[7/8] Building merged manuscript-friendly diagnostic table...', flush=True)
T7=time.perf_counter()

# -----------------------------------------------------------
# 7. Manuscript-friendly merged descriptive/diagnostic table
# -----------------------------------------------------------
# Merge CI, Shapiro p, and outlier counts into the same wide structure used previously.
wide = ci_paper.copy()
for metric_short, metric_label in [('Time_s','Time'),('Subtours','Subtours'),('Quality','Quality')]:
    n = normality[normality['Metric']==metric_label][['Profile','SMF','L','r','s','Shapiro_p']].rename(columns={'Shapiro_p':f'{metric_label}_Shapiro_p'})
    o = outlier_paper[outlier_paper['Metric']==metric_label][['Profile','SMF','L','r','s','N_outliers','Outlier_percent']].rename(columns={'N_outliers':f'{metric_label}_N_outliers','Outlier_percent':f'{metric_label}_Outlier_percent'})
    wide = wide.merge(n,on=['Profile','SMF','L','r','s'],how='left').merge(o,on=['Profile','SMF','L','r','s'],how='left')
wide.to_csv(OUT/'rs_sensitivity_combined_descriptive_diagnostics_all_profiles.csv',index=False)

print(f'[7/8] Done in {time.perf_counter()-T7:.2f} s.', flush=True)
print('[8/8] Writing validation summary and ZIP archive...', flush=True)
T8=time.perf_counter()

# -----------------------
# 8. Validation summaries
# -----------------------
# Validate Moderate inferential results against values reported in the prior run.
moderate_omni = omnibus[omnibus['Profile']=='Moderate'][['Family','Metric','N_complete_pairs','Friedman_chi2','p','Kendalls_W','Significant_0.05']]

summary_lines=[]
summary_lines.append('ALL-PROFILE r/s SENSITIVITY REANALYSIS')
summary_lines.append('='*60)
summary_lines.append(f'Input rows: {len(df)}')
summary_lines.append(f'Profiles: {sorted(df.Profile.unique())}')
summary_lines.append(f'All statuses: {df.Status.value_counts().to_dict()}')
summary_lines.append('')
summary_lines.append('FRIEDMAN OMNIBUS TESTS')
summary_lines.append(omnibus[['Profile','L','Family','Metric','N_complete_pairs','Friedman_chi2','p','Kendalls_W','Significant_0.05']].to_string(index=False))
summary_lines.append('')
summary_lines.append('PAIRWISE WILCOXON TESTS')
summary_lines.append(pairwise[['Profile','L','Family','Metric','Setting1','Setting2','N_pairs','Median_delta_2_minus_1','Mean_delta_2_minus_1','p_raw','p_Holm','Rank_biserial_2_minus_1','Significant_0.05']].to_string(index=False))
summary_lines.append('')
summary_lines.append('NORMALITY SUMMARY')
summary_lines.append(f"Shapiro tests: {len(normality)}; rejected at 0.05: {(normality['Shapiro_p']<0.05).sum()}")
summary_lines.append('')
summary_lines.append('OUTLIER SUMMARY')
summary_lines.append(f"Configuration-outcome combinations: {len(outlier_paper)}")
summary_lines.append(f"Combinations with >=1 outlier: {(outlier_paper['N_outliers']>0).sum()}")
summary_lines.append(f"Total flagged observations across combinations: {int(outlier_paper['N_outliers'].sum())}")
summary_lines.append('')
summary_lines.append('CENSORING SUMMARY')
summary_lines.append(f"Timeouts: {int(surv_summary['N_TIMEOUT'].sum())}; Errors: {int(surv_summary['N_ERROR'].sum())}")
(OUT/'sensitivity_all_profiles_key_results.txt').write_text('\n'.join(summary_lines), encoding='utf-8')

# Bundle outputs
zip_path = ANALYSIS_ROOT / 'sensitivity_all_profiles_analysis_outputs.zip'
with zipfile.ZipFile(zip_path,'w',compression=zipfile.ZIP_DEFLATED) as z:
    for p in sorted(OUT.glob('*')):
        if p.is_file(): z.write(p, arcname=p.name)

print(f'[8/8] Done in {time.perf_counter()-T8:.2f} s.', flush=True)
print(f'Total elapsed: {time.perf_counter()-T0:.2f} s', flush=True)
print('Created outputs in', OUT)
print('Zip:', zip_path)
print('\nFriedman tests:\n', omnibus[['Profile','Family','Metric','Friedman_chi2','p','Kendalls_W','Significant_0.05']].to_string(index=False))
print('\nNormality rejected:', int((normality['Shapiro_p']<0.05).sum()), '/', len(normality))
print('Outlier combinations:', int((outlier_paper['N_outliers']>0).sum()), '/', len(outlier_paper), ' total flagged=', int(outlier_paper['N_outliers'].sum()))
print('Timeouts=', int(surv_summary['N_TIMEOUT'].sum()), 'Errors=', int(surv_summary['N_ERROR'].sum()))
